
name: atm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.5
  - setuptools
  - wheel
  - pip:
      - PyYAML
      - bddl
      - click
      - cloudpickle
      - cmake
      - deepspeed
      - diffusers
      - easydict
      - egl-probe
      - einops
      - environs
      - flow-vis
      - future
      - gdown
      - glfw
      - gym
      - gymnasium
      - h5py
      - huggingface-hub
      - hydra-core
      - imageio
      - imageio-ffmpeg
      - ipdb
      - ipykernel
      - ipython
      - json5
      - jupyterlab
      - keras
      - lightning
      - lightning-utilities
      - line-profiler
      - lit
      - llvmlite
      - matplotlib
      - matplotlib-inline
      - mediapy
      - moviepy
      - mujoco
      - natsort
      - ninja
      - notebook
      - notebook-shim
      - numba
      - numpy
      - omegaconf
      - opencv-python
      - pandas
      - pybullet-svl
      - pynput
      - pytorch-lightning
      - pyyaml
      - scikit-learn
      - scipy
      - tensorboard
      - tensorboard-data-server
      - tensorflow
      - tensorflow-estimator
      - tensorflow-hub
      - tensorflow-io-gcs-filesystem
      - tensorflow-metadata
      - termcolor
      - tf-keras
      - tfds-nightly
      - timm
      - tokenizers
      - torch
      - torchvision
      - tqdm
      - transformers
      - wandb

